apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ssan
  name: ssan
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssan
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ssan
    spec:
      containers:
      - image: alekovg/16san
        name: ssan
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ssan
  name: ssan
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: ssan
  type: ClusterIP
status:
  loadBalancer: {}
