apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ssan
  name: ssan
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ssan
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ssan
    spec:
      restartPolicy: Always
      containers:
      - image: alekovg/16san
        name: ssan
        resources:
          requests:
            cpu: 300m
          limits:
            cpu: 500m
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ssan
  name: ssan
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: ssan
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ssan-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ssan
  minReplicas: 2
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70