apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ssan-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ssan-service
                port:
                  number: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ssan
  name: ssan
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ssan
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ssan
    spec:
      restartPolicy: Always
      containers:
        - image: alekovg/ssan-app
          name: ssan
          resources:
            requests:
              cpu: 1000m
            limits:
              cpu: 1500m
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: ssan
  name: ssan-service
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ssan
  type: LoadBalancer
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ssan-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ssan
  minReplicas: 3
  maxReplicas: 8
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 70